CREATE TABLE IF NOT EXISTS USER
(
    id   BIGINT   NOT NULL AUTO_INCREMENT COMMENT '고유 ID',
    name VARCHAR2 NOT NULL COMMENT '이름',
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS FRIEND
(
    id   BIGINT   NOT NULL AUTO_INCREMENT COMMENT '고유 ID',
    name VARCHAR2 NOT NULL COMMENT '이름',
    PRIMARY KEY (id)
);